name: build-and-test

on:
  pull_request:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: |
        curl -OL https://github.com/alire-project/alire/releases/download/v1.1.1/alr-1.1.1-bin-x86_64-linux.zip
        unzip alr-1.1.1-bin-x86_64-linux.zip
        bin/alr build -n
