name: build-and-test

on:
  pull_request:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build project
      run: |
        sudo apt-get update
        sudo apt-get install alire gprbuild gnat
        alr build
